name:                hs-delay
version:             0.1.0.0
github:              "d8euAI8sMs/scm-1-delay"
license:             Apache-2.0
author:              "Alexander Vasilevsky"
maintainer:          "a.kalaider@yandex.ru"
copyright:           "2019 kalaider"
build-type:          Custom

description:         Please see the README on GitHub at <https://github.com/d8euAI8sMs/scm-1-delay#readme>

custom-setup:
  dependencies:
  - base >= 4.7 && < 5
  - Cabal == 2.4.*
  - directory == 1.3.*

dependencies:
- base >= 4.7 && < 5
- random
- split
- vector
- parallel

library:
  include-dirs: ..\..\include
  source-dirs: src
  extra-libraries: DelayGUI

executables:
  hs-delay:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-delay
